# Generated by Django 2.0.7 on 2018-12-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
